name: Deploy Notebooks to Databricks

on:
  push:
    branches: [ main ]   # Trigger on pushes to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Configure Databricks CLI
        run: |
          databricks configure --token --host ${{ secrets.https://dbc-77a31924-3e78.cloud.databricks.com }}
        env:
          DATABRICKS_TOKEN: ${{ secrets.dapi046ab70b950c98993ab4bb9bbe5393f5 }}

      - name: Deploy notebooks to workspace
        run: databricks workspace import_dir ./notebooks /Shared/notebooks -o
